/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Native */

#ifndef _Included_Native
#define _Included_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Native
 * Method:    createValidityChecker
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Native_createValidityChecker
  (JNIEnv *, jclass);

/*
 * Class:     Native
 * Method:    bvType
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_Native_bvType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     Native
 * Method:    varExpr
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_Native_varExpr
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     Native
 * Method:    bvConstExprFromInt
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_Native_bvConstExprFromInt
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     Native
 * Method:    vc_bvPlusExpr
 * Signature: (JIJJ)J
 */
JNIEXPORT jlong JNICALL Java_Native_vc_1bvPlusExpr
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

/*
 * Class:     Native
 * Method:    vc_eqExpr
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_Native_vc_1eqExpr
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     Native
 * Method:    vc_notExpr
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_Native_vc_1notExpr
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     Native
 * Method:    vc_query
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_Native_vc_1query
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     Native
 * Method:    vc_printCounterExample
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Native_vc_1printCounterExample
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Native
 * Method:    vc_Destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Native_vc_1Destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
